name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode GCP credentials
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > $HOME/gcp-key.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: my-app-66312
        service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
        export_default_credentials: true

    - name: Authenticate manually (refuerzo)
      run: |
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

    - name: Sync files to GCS
      run: |
        gsutil -m rsync -r ./ gs://www.stojangasic.com/
        gsutil -m setmeta -h "Cache-Control:no-cache,max-age=0" $(gsutil ls gs://www.stojangasic.com/**)
